export const CELLAR_MODEL = {
  normal: {
    A: [
      "corner--left-top",
      "wall--top",
      "wall--top",
      "wall--top",
      "wall--top",
      "wall--top",
      "wall--top",
      "wall--top",
      "corner--right-top",
    ],
    B: [
      "wall--left",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "wall--right",
    ],
    C: [
      "wall--left",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "wall--right",
    ],
    D: [
      "wall--left",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "wall--right",
    ],
    E: [
      "wall--left",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "wall--right",
    ],
    F: [
      "wall--left",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "wall--right",
    ],
    G: [
      "wall--left",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "wall--right",
    ],
    H: [
      "wall--left",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "floor",
      "wall--right",
    ],
    I: [
      "corner--left-bottom",
      "wall--bottom",
      "wall--bottom",
      "wall--bottom",
      "wall--bottom",
      "wall--bottom",
      "wall--bottom",
      "wall--bottom",
      "corner--right-bottom",
    ],
  },
  cell: {
    right: {
      A: [
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
      ],
      B: [
        "dark-board",
        "corner--left-top",
        "wall--top",
        "wall--top",
        "wall-torch--top",
        "wall--top",
        "wall--top",
        "corner--right-top",
        "dark-board",
      ],
      C: [
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "floor",
        "floor",
        "cuoin--right-top",
        "corner--right-top",
      ],
      D: [
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "floor",
        "floor",
        "floor",
        "wall--right",
      ],
      E: [
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "floor",
        "floor",
        "floor",
        "dark-board",
      ],
      F: [
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "floor",
        "floor",
        "floor",
        "wall--right",
      ],
      G: [
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "floor",
        "floor",
        "cuoin--right-bottom",
        "corner--right-bottom",
      ],
      H: [
        "dark-board",
        "corner--left-bottom",
        "wall--bottom",
        "wall--bottom",
        "wall--bottom",
        "wall--bottom",
        "wall--bottom",
        "corner--right-bottom",
        "dark-board",
      ],
      I: [
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
        "dark-board",
      ],
    },
  },
  corridor: {
    vertical: {
      A: [
        "dark-board",
        "dark-board",
        "corner--left-top",
        "wall--top",
        "wall--top",
        "wall--top",
        "corner--right-top",
        "dark-board",
        "dark-board",
      ],
      B: [
        "dark-board",
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "wall--right",
        "dark-board",
        "dark-board",
      ],
      C: [
        "dark-board",
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "wall--right",
        "dark-board",
        "dark-board",
      ],
      D: [
        "dark-board",
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "wall--right",
        "dark-board",
        "dark-board",
      ],
      E: [
        "dark-board",
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "wall--right",
        "dark-board",
        "dark-board",
      ],
      F: [
        "dark-board",
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "wall--right",
        "dark-board",
        "dark-board",
      ],
      G: [
        "dark-board",
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "wall--right",
        "dark-board",
        "dark-board",
      ],
      H: [
        "dark-board",
        "dark-board",
        "wall--left",
        "floor",
        "floor",
        "floor",
        "wall--right",
        "dark-board",
        "dark-board",
      ],
      I: [
        "dark-board",
        "dark-board",
        "corner--left-bottom",
        "wall--bottom",
        "wall--bottom",
        "wall--bottom",
        "corner--right-bottom",
        "dark-board",
        "dark-board",
      ],
    },
  },
};
